---
title: "DataCleanupExpression"
author: "Spring"
date: "06 6 2021"
output:
  html_document: default
  pdf_document: default
---

```{r}
load("Data/prism_datasets.rda")
load("Data/cellline_datasets.rda")

```

Spring presents
## prism.exp dataset

### 1. creating the dataset *prism.exp.pan* 

*prism.exp.pan* contains the prism.exp data frame with just the relevant cancer cell lines

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# to get an approximate overview
str(prism.exp)

# In order to extract the desired cell lines, we need the Depmap IDs of the desired pancreatic cancer celllines. We get the desired Depmap ID's using the prism.cl data set and the subset function. The subset function returns rows of a data frame, which meet the desired condition. We save the reduced prism.cl data set as the cl.metadata.exp variable. 
cl.metadata.exp = subset(prism.cl, Type_for_Manuscript == "Pancreatic" )

# Using the previously created data frame, we extract the first column, which contains DepmapID's, and assign them to the Pancreatic.cl.vector. This vector contains Depmap ID's of all pancreatic cancer cell lines in our dataset.
pan.cl.Vector = cl.metadata.exp[,1]

# There are 33 pancreatic cancer cellines
length(pan.cl.Vector)

# Because the rownames of prism.exp are DepmapID's, it is now possible to reduce the prism.exp dataset to the desired cell lines.
prism.exp.pan = prism.exp[pan.cl.Vector,]


###     !!! please note, that you can reach a function package including a function to extract pancreatic cancer data points from any of the cell line * x data frames. 
###     !!! the package can be loaded through:  "source("Scripts/Functions.R")" with a working directory of the git rep (can be checked via:  "getwd()")
```


Check for NAs

```{r}
expressionNAcheck = is.na(prism.exp.pan)
sum(expressionNAcheck)
rm(expressionNAcheck)
```
There are no NAs.





Sorting the genes by Expression level

```{r setup, include=FALSE}

# mean value for every column of prism.exp.pancreatic
meanval.prism.exp.pan = apply(prism.exp.pan, 2, function(x){mean(x)})

# standard deviation value for every column of prism.exp.pancreatic
sd.prism.exp.pan = apply(prism.exp.pan, 2, function(x){sd(x)})


var.prism.exp.pan = apply(prism.exp.pan, 2, function(x){var(x)})

#sort and order

#welche gene am haeufigsten
sorted.meanval.exp.pan = sort(meanval.prism.exp.pan, decreasing = TRUE, na.last = TRUE)

#prism.exp.pancreatic neu nach mean sortiert
ordered.meanval.prism.exp.pan = order(meanval.prism.exp.pan, decreasing = TRUE, na.last = TRUE)
meansorted.prism.exp.pan = prism.exp.pan[,ordered.meanval.prism.exp.pan]

#prism.exp.pancreatic neu nach sd sortiert
ordered.sd.prism.exp.pan = order(sd.prism.exp.pan, decreasing = TRUE, na.last = TRUE)
sdsorted.prism.exp.pan = prism.exp.pan[,ordered.sd.prism.exp.pan]

```




```{r}

hist(meanval.prism.exp.pan,
     freq = TRUE,
     main = "Summary mean expression Values",
     xlab = "Mean expression Values",
     ylab = "Counts of Mean expression Values",
     plot = TRUE,
     breaks = "fd")


hist(sd.prism.exp.pan,
     freq = TRUE,
     main = "Summary sd expression Values",
     xlab = "Sd expression Values",
     ylab = "Counts of sd expression Values",
     plot = TRUE,
     breaks = "fd")

hist(var.prism.exp.pan,
     freq = TRUE,
     main = "Summary var expression Values",
     xlab = "var expression Values",
     ylab = "Counts of var expression Values",
     plot = TRUE,
     breaks = "fd")
```



Performing a Z-Transformation
```{r}
prism.exp.pan.Z = scale(prism.exp.pan)

# mean value for every column of prism.exp.pancreatic
meanval.prism.exp.pan.Z = apply(prism.exp.pan.Z, 2, function(x){mean(x)})

# standard deviation value for every column of prism.exp.pancreatic
sd.prism.exp.pan.Z = apply(prism.exp.pan.Z, 2, function(x){sd(x)})


hist(meanval.prism.exp.pan.Z,
     freq = TRUE,
     main = "Summary mean expression Values",
     xlab = "Mean expression Values",
     ylab = "Counts of Mean expression Values",
     plot = TRUE,
     breaks = "fd")


hist(sd.prism.exp.pan.Z,
     freq = TRUE,
     main = "Summary sd expression Values",
     xlab = "Sd expression Values",
     ylab = "Counts of sd expression Values",
     plot = TRUE,
     breaks = "FD")
```





Destinction between primary and metastasis celllines

```{r}

#depmap IDs of primary pancreatic cell lines
primary.pan.cl.df = subset(cl.metadata.exp, primary_or_metastasis == "Primary" )
primary.pan.cl.Vector = primary.pan.cl.df[,1]


#depmap IDs of metastasic pancreatic cell lines
metastasis.pan.cl.df = subset(cl.metadata.exp, primary_or_metastasis == "Metastasis" )
metastasis.pan.cl.Vector = metastasis.pan.cl.df[,1]

```

