---
title: "Regression Analysis"
author: "Autumn"
date: "14/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("Scripts/Initiator.R")
th <- "q.001, q.005"
source("./Scripts/EfDrIdentifier.R")
```

Interesting drug>>

```{r}
.env.ra <- new.env(parent = .GlobalEnv)

pancan.achilles <- row.col.cleaner(prism.extractor(prism.achilles))

for (i in 1:5) { 
  .env.ra[[paste("dr.ef.pancan.max.", i, sep = "")]] <- dr.to.effect(ef.pancan.perdrug, doscor = 2)[i]
  .env.ra[[paste("id.dr.ef.pancan.max.", i, sep = "")]] <- as.character(unique(prism.treat[which(prism.treat[, "name"]==names(get(paste("dr.ef.pancan.max.", i, sep = ""), pos = .env.ra))), "broad_id"]))
  .env.ra[[paste("ef.pancan.max.percl.", i, sep = "")]] <- pancan.perdrug[, get(paste("id.dr.ef.pancan.max.", i, sep = ""), pos = .env.ra)]
  names(.env.ra[[paste("ef.pancan.max.percl.", i, sep = "")]]) <- rownames(pancan.perdrug)
  .env.ra[[paste("ef.pancan.max.percl.", i, sep = "")]] <- get(paste("ef.pancan.max.percl.", i, sep = ""), pos = .env.ra)[!is.na(get(paste("ef.pancan.max.percl.", i, sep = ""), pos = .env.ra))]
  
  del <- c(NULL)
  for (j in 1:length(.env.ra[[paste("ef.pancan.max.percl.", i, sep = "")]])) {
    if (sum(grepl(names(get(paste("ef.pancan.max.percl.", i, sep = ""), pos = .env.ra))[j], rownames(pancan.achilles)))==0) {del <- append(del, j)}
  }
  if(!is.null(del)) {
    .env.ra[[paste("ef.pancan.max.percl.", i, sep = "")]] <- .env.ra[[paste("ef.pancan.max.percl.", i, sep = "")]][-rev(del)]
  }
  del <- c(NULL)
  for (j in 1:nrow(pancan.achilles)) {
    if (!{rownames(pancan.achilles)[j] %in% names(get(paste("ef.pancan.max.percl.", i, sep = ""), pos = .env.ra))}) del <- append(del, j)
  }
  if(!is.null(del)) {
    .env.ra[[paste("pancan.achilles.fitted.", i, sep = "")]] <- pancan.achilles[-rev(del), ]
  } else .env.ra[[paste("pancan.achilles.fitted.", i, sep = "")]] <- pancan.achilles
}

env.ra.vars <- ls(pos = .env.ra); env.ra.vars
env.ra.vars.grpd <- lapply(0:3, function(i) return(env.ra.vars[{1+(i*5)}:{5+(i*5)}])); env.ra.vars.grpd
```

Interesting achilles genes>>

```{r}
pancan.achilles.na.imp <- df.NA.to.val(.env.ra$pancan.achilles.fitted.1, 2, "median")

topVar <- apply(pancan.achilles.na.imp, 2, var) 
summary(topVar)
pancan.achilles.topVar <- pancan.achilles.na.imp[, topVar > quantile(topVar, probs = 0.95, na.rm = T)] 
dim(pancan.achilles.topVar)
```


```{r}
models <- list()
for (i in 1:(ncol(pancan.achilles.topVar))) {
  models[[i]] <- summary(lm(.env.ra$ef.pancan.max.percl.1 ~ pancan.achilles.topVar[, i]))
}
length(models)

r2 <- c()

for (i in 1:length(models)) {
  r2 <- append(r2, unlist(models[[i]]$r.squared))
}
names(r2) <- colnames(pancan.achilles.topVar)
length(r2)
max(r2); min(r2)
names(r2[which(r2 == max(r2))]); names(r2[which(r2 == min(r2))])
unname(which(r2 == max(r2)))
```


```{r}
plot(pancan.achilles.topVar[, 432], .env.ra$ef.pancan.max.percl.1, ylab = paste("Efficacy per dosage of", ef.pancan.perdrug[1]), xlab = paste("Achilles value of", names(r2[which(r2 == max(r2))])), main = paste("Correlation of", names(r2[which(r2 == max(r2))]), "with", ef.pancan.perdrug[1], "at r.squared =", round(max(r2), digits = 5)))
abline(lm(.env.ra$ef.pancan.max.percl.1 ~ pancan.achilles.topVar[, 432]))
```


```{r}
pancan.achilles.na.imp <- df.NA.to.val(.env.ra$pancan.achilles.fitted.2, 2, "median")

topVar <- apply(pancan.achilles.na.imp, 2, var) 
summary(topVar)
pancan.achilles.topVar <- pancan.achilles.na.imp[, topVar > quantile(topVar, probs = 0.95, na.rm = T)] 
dim(pancan.achilles.topVar)
```


```{r}
models <- list()
for (i in 1:(ncol(pancan.achilles.topVar))) {
  models[[i]] <- summary(lm(.env.ra$ef.pancan.max.percl.2 ~ pancan.achilles.topVar[, i]))
}
length(models)

r2 <- c()

for (i in 1:length(models)) {
  r2 <- append(r2, unlist(models[[i]]$r.squared))
}
names(r2) <- colnames(pancan.achilles.topVar)
length(r2)
max(r2); min(r2)
names(r2[which(r2 == max(r2))]); names(r2[which(r2 == min(r2))])
unname(which(r2 == max(r2)))
```


```{r}
plot(pancan.achilles.topVar[, 259], .env.ra$ef.pancan.max.percl.2, ylab = paste("Efficacy per dosage of", ef.pancan.perdrug[2]), xlab = paste("Achilles value of", names(r2[which(r2 == max(r2))])), main = paste("Correlation of", names(r2[which(r2 == max(r2))]), "with", ef.pancan.perdrug[2], "at r.squared =", round(max(r2), digits = 5)))
abline(lm(.env.ra$ef.pancan.max.percl.2 ~ pancan.achilles.topVar[, 259]))
```

