library(knitr)
library(cluster)
library(tibble)
library(ggplot2)
library(dplyr)
library(compiler)
library(svDialogs)
library(ggpubr)
load("Data/prism_datasets.rda", envir = .GlobalEnv)
load("Data/cellline_datasets.rda", envir = .GlobalEnv)
rownames(prism.cl) <- prism.cl[, "DepMap_ID"]